import classes from "./TermsAndConditions.module.scss";

export default function TermsAndConditions() {
    return (
        <main className={classes.terms}>
            <h1>ARDO Group Limited</h1>
            <h2>Terms and Conditions</h2>
            <p>Last Updated: April 26, 2024</p>
            <h3>1. Acceptance of Terms.</h3>
            <p>1.1 ARDO Group Limited (“ARDO”) provides its Services (as defined in Section 2.1 below) to you through its website located at <a href={"https://ardogroup.org"} target={"_blank"}>https://ardogroup.org</a>(the “Site”), subject to this Terms and Conditions (“T&C”). By accepting this T&C or by accessing or using the Services or Site, you acknowledge that you have read, understood, and agree to be bound by this T&C. You acknowledge that this T&C is a contract between you and ARDO, even though it is electronic and is not physically signed by you and ARDO. If you are entering into this T&C on behalf of a corporation, limited liability company, business, or other legal entity, you represent that you have the authority to bind such entity and its affiliates to this T&C, in which case the terms “you” or “your” shall refer to such entity and its affiliates. If you do not have such authority, or if you do not agree with this T&C, you must not accept this T&C and may not use the Services. Certain terms will only be applicable if You enter into a Supplier Agreement or Buyer Agreement and are noted below in these T&C.</p>
            <p>1.2 As part of the registration process, you will identify an administrative username and password for your account (“Account”). Each Account may only have one user.</p>
            <p>1.3 ARDO may change this T&C from time to time by providing you ten (10) days prior notice either by emailing the email address associated with your Account or by posting a notice on the Site. You can review the most current version of this T&C at any time at <a href={"https://ardogroup.org"} target={"_blank"}>https://ardogroup.org</a>. The revised terms and conditions will supersede any previously posted terms and become effective ten (10) days after we post or send you notice of such changes, and if you use the Services after that date, your use will constitute acceptance of the revised terms and conditions. If any change to this T&C is not acceptable to you, your only remedy is to stop using the Services and send a cancellation email to info@ardogroup.org. For the avoidance of doubt, the Parties acknowledge and understand that any and all separately negotiated and agreed-upon agreements between the Parties will supersede this T&C and terms set forth herein.</p>
            <h3>2. Definitions.</h3>
            <p>2.1 The “Services” includes (a) the Site, (b) ARDO’s proprietary platform connecting buyers and sellers of surplus produce and related technologies and services, and (c) all software (including the Software, as defined in Section 3.3 below), data, reports, text, images, sounds, video, and content made available through any of the foregoing (collectively referred to as the “Content”). Any new features added to or augmenting the Services are also subject to this T&C.</p>
            <p>2.2 “Surplus Produce” shall mean produce which when sold is imperfect in appearance or surplus produce, and which is wholesome and safe for human consumption; and “Surplus Produce Platform” shall mean any business or platform (whether by website, technology application, direct sales or otherwise) the purpose of which is to connect suppliers and buyers of Deliverables (defined below in Section 4.2) or to distribute Deliverables.</p>
            <p>2.3 The “Term” shall commence upon the date that you create an Account, and, unless earlier terminated as provided for herein, shall continue for twelve (12) months (the “Initial Term”), at which point, the T&C shall automatically renew for successive six (6) month periods (a “Renewal Term” and, together with the Initial Term, the “Term”) unless either party gives notice of its intent not to renew at least thirty (30) day prior to the start of the next Renewal Term.</p>
            <p>2.3.1 For Suppliers - For any supplier agreement entered into between ARDO and You (hereinafter “Supplier Agreement”) shall be effective for one (1) year from the date of execution by both Parties (the “Initial Term”), at which point, the Agreement shall automatically renew for successive one (1) year periods (a “Supplier Renewal Term” and, together with the Initial Term, the “Term”) unless either Party gives notice of its intent not to renew at least thirty (30) day prior to the start of the next Renewal Term.</p>
            <p>2.3.2 For Buyers - For any buyer agreement entered into between ARDO and You (hereinafter “Buyer Agreement”) shall be effective for (12) months from the date of execution by both Parties (the “Initial Term”), at which point, the Agreement shall automatically renew for successive six (6) month periods (a “Renewal Term” and, together with the Initial Term, the “Term”) unless either Party gives notice of its intent not to renew at least thirty (30) day prior to the start of the next Renewal Term.</p>
            <h3>3. General Conditions; Access and Use of the Services.</h3>
            <p>3.1 During the Term and for one (1) year thereafter you will not directly or indirectly (i) encourage or solicit any partner, supplier, vendor, or customer of ARDO to provide or sell you produce (including Surplus Produce) or provide services similar to the Services provided by ARDO (except as contemplated by this T&C and solely in connection with your relationship with ARDO), for any reason; (ii) encourage or solicit any employee or consultant of ARDO to leave ARDO for any reason, or (iii) operate a Surplus Produce Platform or otherwise engage in any activity that is in any way competitive with the business of ARDO. For clarity, unless you first learned of the specific produce (including Surplus Produce) opportunity from ARDO or the Site, the prohibitions set forth in subsection (i) of this Section 3.1 shall not apply to the extent you had a prior business relationship with such entities.</p>
            <p>3.2 Subject to the terms and conditions of this T&C, you may access and use the Services only for lawful purposes. ARDO owns all right, title and interest (including all intellectual property rights of any sort) relating to any and all designs, know-how, ideas and information relating to ARDO’s Surplus Produce Platform or any Proprietary Information (as defined in Section 3.4 below). All rights, title, and interest in and to the Services and its components will remain with and belong exclusively to ARDO. You shall not (a) sublicense, resell, rent, lease, transfer, assign, timeshare, or otherwise commercially exploit or make the Service available to any third party; (b) use the Services in any unlawful manner (including without limitation in violation of any data, privacy or export control laws) or in any manner that interferes with or disrupts the integrity or performance of the Services or its components, or (c) modify, adapt or hack the Services to, or otherwise attempt to gain unauthorized access to the Services or its related systems or networks. You shall comply with any codes of conduct, policies, or other notices ARDO provides you or publishes in connection with the Services, and you shall promptly notify ARDO if you learn of a security breach related to the Services.</p>
            <p>3.3 Any software that may be made available by ARDO in connection with the Services (“Software”) contains proprietary and confidential information that is protected by applicable intellectual property and other laws. Subject to the terms and conditions of this T&C, ARDO hereby grants you a revocable, non-transferable, non-sublicensable and non-exclusive right and license to use the object code of any Software solely in connection with the Services, provided that you shall not (and shall not allow any third party to) copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code or sell, assign, sublicense or otherwise transfer any right in any Software. You agree not to access the Services by any means other than through the interface that is provided by ARDO for use in accessing the Services. Any rights not expressly granted herein are reserved and no license or right to use any trademark of ARDO or any third party is granted to you in connection with the Services.</p>
            <p>3.4 You agree that all business, technical, and financial information (including, without limitation, the identity of and information relating to partners, suppliers, vendors, customers, or employees) learned or obtained by you from ARDO or the Surplus Produce Platform that relate to ARDO’s business or the Services, are “Proprietary Information.” You agree to hold in confidence and not disclose or use any Proprietary Information, except in performing or receiving performance of the Services. Upon termination of this T&C, or as otherwise requested by ARDO, you agree to destroy all items and copies of Proprietary Information, except that you may keep copies of your commercial records, invoices, and this T&C.</p>
            <p>3.5 You are solely responsible for all data, information, feedback, suggestions, text, content, and other materials that you upload, post, deliver, provide, or otherwise transmit or store (hereafter “post(ing)”) in connection with or relating to the Services (“Your Content”). For every email sent outside of your organization via the Services, you acknowledge and agree that ARDO shall have the right to automatically add an identifying footer in accordance with our standard policies then in effect you agree to cooperate with and provide reasonable assistance to ARDO in promoting and advertising the Services.</p>
            <p>3.6 You are responsible for maintaining the confidentiality of your login, password and Account and for all activities that occur under your login or Account. ARDO reserves the right to access your Account as we deem appropriate, including in order to respond to your requests for technical support, for reasons related to the review and/or improvement of the Services, and for our own business purposes. By posting Your Content on or through the Services, you hereby do and shall grant ARDO a worldwide, non-exclusive, perpetual, irrevocable, royalty-free, fully paid, sublicensable, and transferable license to use, modify, reproduce, distribute, display, publish and perform Your Content in connection with the Services. ARDO has the right, but not the obligation, to monitor the Services, Content, or Your Content. You further agree that ARDO may remove or disable any Content, and Your Content at any time for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities), or for no reason at all.</p>
            <p>3.7 Upon creating your Account, you understand and consent to ARDO sending you (including via email) information regarding the Services, including but not limited to (a) notices about your use of the Services, including transaction confirmations; (b) updates to the Services and new features or products; (c) administrative messages and other information; and (d) advertising, marketing, promotions, and other materials regarding ARDO’s products and services. Notices will be sent to you via the contact information associated with your Account. You may choose to opt out of receiving advertising, marketing, and promotional emails by following the unsubscribe link located at the bottom of such emails.</p>
            <p>3.8 ARDO shall have the right to collect and analyze data and other information relating to the provision, use and performance of various aspects of the Services (including, without limitation, information concerning Your Content, data and data derived therefrom), and ARDO shall be free (during and after the Term) to use such information and data to develop and improve (including for diagnostic and corrective purposes) the Services and other ARDO offerings, and to disclose such data for our business purposes. No rights or licenses are granted except as expressly set forth herein.</p>
            <p>3.9 You understand that the operation of the Services, including Your Content, may be unencrypted and involve (a) transmissions over various networks; (b) changes to conform and adapt to technical requirements of connecting networks or devices and (c) transmission to ARDO’s third party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to operate and maintain the Services. Accordingly, you acknowledge that you bear sole responsibility for adequate security, protection, and backup of Your Content. ARDO will have no liability to you for any unauthorized access or use of any of Your Content, or any corruption, deletion, destruction, or loss of any of Your Content.</p>
            <p>3.10 You shall be responsible for obtaining and maintaining any equipment and ancillary services needed to connect to, access, or otherwise use the Services, including, without limitation, modems, hardware, server, software, operating system, networking, web servers, long distance and local telephone service (collectively, “Equipment”). You shall be responsible for ensuring that such Equipment is compatible with the Services (and, to the extent applicable, the Software) and complies with all configurations and specifications set forth in ARDO’s published policies then in effect. You shall also be responsible for maintaining the security of the Equipment, your Account, passwords (including but not limited to administrative and user passwords), and files, and for all uses of your Account or the Equipment with or without your knowledge or consent.</p>
            <p>3.11 ARDO reserves the right to use your name and/or business name as a reference for marketing or promotional purposes on ARDO’s website and in other communication with existing or potential ARDO customers. To decline ARDO this right you need to email info@ardogroup.org stating that you do not wish to be used as a reference.</p>
            <p>3.12 Subject to the terms hereof, ARDO may (but has no obligation to) provide technical support services, through email in accordance with our then-current standard practices.</p>
            <h3>4. Delivery; Acceptance/Rejection of Deliverables; Payment.</h3>
            <p>4.1 Delivery terms shall be defined by the Centre for Food Safety (“CFS”). The applicable purchase order, term sheet, or other document will indicate whether the order is to be picked up by you (“FOB”) or delivered by ARDO. If the product is FOB, then you assume all risks of loss and damage in transit.</p>
            <p>4.2 You shall have 3 hours to accept or reject goods offered in connection with the Services (“Deliverables”) upon your receipt of the Deliverables. Deliverables may include goods of all types, including Surplus Produce and goods not covered by CFS. Any rejection must be in writing, via an email to your main contact at ARDO. Your failure to notify ARDO of rejection within 3 hours of receipt shall result in automatic acceptance of the Deliverables. In case of a reasonable rejection of Deliverables by you, the parties agree to work together in good faith to minimize mutual damages and to cure any such non-conformance to the satisfaction of both parties. Since ARDO provides a service and operates the Surplus Produce Platform to connect suppliers and buyers, the parties agree that ARDO does not take title to the Deliverables.</p>
            <p>4.3 Pursuant to CFS regulations and statutory trust provisions, any payment terms beyond three days must be reflected by a written agreement. In compliance with these regulations and provisions, this T&C will confirm that payment terms for transactions entered into between you and ARDO Technologies, Inc. shall be 3 days from receipt of goods. You may be required to select a payment option and provide ARDO information regarding your credit card or other payment instrument. You represent and warrant to ARDO that such information is true and that you are authorized to use the payment instrument. You will promptly update your Account information with any changes (for example, a change in your billing address or credit card expiration date) that may occur. You agree to pay ARDO the amount that is specified in the payment option in accordance with the terms of any payment instrument and this T&C. You hereby authorize ARDO to bill your payment instrument in accordance with the terms of the applicable payment option until you terminate your Account, and you further agree to pay any charges so incurred. If you dispute any charges you must let ARDO know within seven (3) days after the date that ARDO invoices you. You shall be responsible for all taxes associated with Services other than Hong Kong taxes based on ARDO’s net income.</p>
            <p>4.4 For Buyers - Delivery; Specifications; Rejection of Deliverable; Payment Terms.</p>
            <p>4.4.1 Delivery terms for Seconds Produce shall be defined by the Centre for Food Safety (“CFS”). Delivery terms for other goods outside the scope of CFS shall be determined by mutual agreement of the Parties. The applicable Purchase Order will indicate whether the order is to be picked up by Buyer (“FOB”) or delivered by ARDO (“Delivered”). If the product is FOB, the Buyer assumes all risks of loss and damage in transit.</p>
            <p>4.4.2 <span style={{textDecoration: "underline"}}>Specifications.</span> Prior to any purchase under this Agreement, Buyer shall have the opportunity to review and agree to specifications for all goods provided by ARDO. By making a purchase Buyer acknowledges that it has agreed to the specifications provided by ARDO.</p>
            <p>4.4.3 <span style={{textDecoration: "underline"}}>Rejection of Deliverables.</span> Buyer shall have 3 hours to accept or reject goods offered in connection with the Services (“Deliverables”) upon Buyer receiving Deliverables. Failure to notify ARDO of rejection within 3 hours of receipt shall result in automatic acceptance of the Deliverables. In case of a reasonable rejection of Deliverables by Buyer, the Parties agree to work together in good faith to minimize mutual damages and to cure any such non-conformance to the satisfaction of both Parties.</p>
            <p>4.4.4 <span style={{textDecoration: "underline"}}>Payment Terms.</span> Pursuant to CFS regulations and statutory trust provisions, any payment terms beyond ten days must be reflected by a written agreement. In compliance with these regulations and provisions, this Agreement will confirm that payment terms for transactions entered into between ARDO Group Limited and Buyer shall be 3 days from receipt of goods.</p>
            <h3>5. Ownership Rights; Proprietary Information; Photos.</h3>
            <p>a. ARDO owns all right, title and interest (including all intellectual property rights of any sort) relating to any and all designs, know-how, ideas and information accessed, used or modified by Supplier relating to the Services or any Proprietary Information (as defined below).</p>
            <p>b. Supplier agrees that all business, technical and financial information (including, without limitation, the identity of and information relating to Buyers, partners, vendors, customers or employees) learned or obtained by Supplier from ARDO or its Surplus Produce Platform that relate to ARDO’s business or the Services, are “Proprietary Information.” Supplier will hold in confidence and not disclose or use any Proprietary Information, except in performing or receiving performance of the Services. Upon termination or as otherwise requested by ARDO, Supplier will destroy all items and copies of Proprietary Information, except that Supplier may keep copies of its commercial records, invoices and this Agreement.</p>
            <p>c. ARDO may request that from time-to-time Supplier provide a photo, video, or other illustration of Supplier’s goods (collectively, an “Image(s)”) to ARDO. By submitting an Image(s) to ARDO Supplier hereby: (i) grants ARDO permission to use the Image in any publication, including on the ARDO Platform, or for any other lawful purpose, without payment or any other consideration; (ii) forever waives any right to royalties or other compensation arising or related to the use of the Image; (iii) authorizes ARDO to edit, crop, alter, copy, exhibit, publish or distribute Images in the sole discretion of ARDO; (iv) waives the right to inspect or approve the finished Image, including its display on the ARDO Platform; (v) acknowledges that ARDO, in its sole discretion, may use the Images you provide - but is under no obligation to do so; (vi) releases ARDO from all claims, demands, and causes of action which you or your photographer may have related to ARDO’s use of the Images; (vii) agrees to indemnify, defend, and hold harmless ARDO from and against any claims related to ARDO’s use of the Images; (viii) represents and warrants to ARDO that (a) the Images you provide fairly and accurately represent the products that you are offering for sale on the ARDO Platform, and (b) that you have the authority to grant the rights and agree to the obligations set forth above.</p>
            <h3>6. Representations and Warranties.</h3>
            <p>6.1 You represent and warrant to ARDO that (i) you have full power and authority to enter into this T&C; (ii) you own all Your Content or have obtained all permissions, releases, rights or licenses required to engage in your posting and other activities (and allow ARDO to perform its obligations) in connection with the Services without obtaining any further releases or consents; (iii) Your Content and other activities in connection with the Services, and ARDO’s exercise of all rights and license granted by you herein, do not and will not violate, infringe, or misappropriate any third party’s copyright, trademark, right of privacy or publicity, or other personal or proprietary right, nor does Your Content contain any matter that is defamatory, obscene, unlawful, threatening, abusive, tortious, offensive or harassing; (iv) your use of the Services will comply with all applicable laws, including, without limitation, all applicable food safety handling, labelling and other applicable food and health related laws and regulations; (v) if your participation in buying and selling through the Services requires a license, you have obtained such license and the license is in full force and effect; and (vi) you are eighteen (18) years of age or older.</p>
            <p>6.2 <span style={{textDecoration: "underline"}}>For Suppliers - Supplier’s Representations and Warranties; Quality Standards; Compliance with Laws; Labeling Information; Packaging; Recall Procedures.</span></p>
            <p>a. Supplier represents and warrants that all goods that Supplier grows, provides, manufactures, processes, and/or packages under this Agreement shall be:</p>
            <p>(i) grown, produced, packed, stored and shipped in accordance with all applicable laws, including all Food Laws. For purposes of this Agreement “Food Laws” means any applicable law, policy or procedure of the Centre for Food Safety (“CFS”), and any other law or regulations relating to the growing, production, ingredients, manufacture, labeling, advertising, promotion, sale, or safety of the goods.</p>
            <p>(ii) manufactured, grown, provided, processed, and packaged strictly in conformity with applicable sanitation standards, such as those set forth by the CFS in suitable conditions so as to avoid any undue deterioration either in quality, shelf life or freshness; and</p>
            <p>(iii) fit and wholesome for human consumption and shall meet all requirements of applicable statutes, rules, and regulations of the Hong Kong; and</p>
            <p>(iv) unless specifically acknowledged in each instance in writing by ARDO, all goods that Supplier grows, provides, manufactures, processes, and/or packages under this Agreement shall be Major Allergen Free; and</p>
            <p>(v) not adulterated or misbranded, and not prohibited by any law, from being introduced into interstate commerce; and</p>
            <p>(vi) grown, produced, packed, stored and shipped in accordance with all needed governmental, administrative and other approvals, licenses, permits and other authorizations and registrations necessary for the marketing, distribution and sale of its goods.</p>
            <p>b. Supplier further represents and warrants that:</p>
            <p>(i) All goods shall be properly labeled by Supplier before shipping with such information as required by and in accordance with all applicable laws and Food Laws relating to each such product;</p>
            <p>(ii) Any pesticides or chemicals used by Supplier on said goods shall comply with the rules and regulations of the CFS, and have been used at authorized times and in conformity with applicable regulations and label/use instructions of the manufacturer. Supplier shall ensure and monitor that products prohibited by the CFS shall not be used on its goods, and that residues of acceptable products or contaminants shall not exceed those levels permitted by the CFS; and</p>
            <p>(iii) Supplier shall maintain an adequate traceability program that will enable Supplier to promptly and accurately trace the goods supplied, or any portion thereof, to its source from any point in the distribution or marketing process;</p>
            <p>(iv) Supplier shall maintain written recall procedures that ensure compliance with applicable laws;</p>
            <p>(v) Supplier shall maintain for a period of at least one (1) year, or longer if required by Food Laws, and make available to ARDO upon request, all records required by Food Laws, as well as all chemical, physical, microbiological, and process tests of the goods, basic ingredients and packaging materials.</p>
            <p>c. If Supplier becomes aware of the existence of any quality or technical problem with goods, including but not limited to a shelf life or contamination problem, Supplier shall immediately notify ARDO and act in accordance with the procedures mutually agreed by the Parties, and in any event, in accordance with any applicable law, including all Food Laws.</p>
            <p>d. Supplier is responsible for any recall related to its goods failing to comply (or allegedly failing to comply) with Food Laws or any laws relating to labeling, the ingredients or any contaminants contained therein. Supplier agrees to indemnify, protect, and hold harmless ARDO from any and all demands, claims, actions, losses, costs and expenses, including reasonable attorneys’ fees, which may arise from any recall of Supplier’s goods and from the breach of any of the warranties herein. Supplier assumes all risk of loss due to asserted food safety issues contemplated by this provision and the representations and warranties herein set forth.</p>
            <p>e. <span style={{textDecoration: "underline"}}>General Representations and Warranties.</span> ARDO represents and warrants that the Services will be performed in a professional and workmanlike manner. Each Party represents and warrants that: (a) they have the full right to perform this Agreement without conflict to any obligation that they may have to others; (b) they will comply with all applicable laws, including Food Laws, in the course of performance under the Agreement (including, without limitation, in the case of Supplier, all applicable food safety handling, labeling, and other applicable food and health related laws and regulations); and (c) if either Party’s performance hereunder requires any license(s) or permit(s), such Party has, and shall maintain, all required licenses and permits.</p>
            <h3>7. Termination.</h3>
            <p>a. ARDO may terminate your Account and this T&C at any time in its sole discretion; in such event, ARDO shall endeavor to provide you with prompt notice via the administrative email address associated with your Account. You may terminate this T&C upon thirty (30) days’ notice, if ARDO breaches any of the terms or conditions of this T&C and fails to promptly cure such breach. ARDO reserves the right to modify or discontinue, temporarily or permanently, the Services (or any part thereof). All of Your Content on the Services (if any) may be permanently deleted by ARDO upon any termination of your Account in its sole discretion. All accrued rights to payment and the terms of Sections 3 -13 shall survive termination of this T&C.</p>
            <p>b. <span style={{textDecoration: "underline"}}>For Suppliers</span> - Under any Supplier Agreement, if either Party breaches a material provision of the Supplier Agreement, the other Party may terminate this Agreement upon ten (10) days’ notice, unless the breach is cured within the ten (10) days. ARDO also may terminate this Agreement at any time, for any reason, without any further liability, upon thirty (30) days’ notice. If such termination occurs, the Parties agree to pay any and all unpaid, undisputed amounts due for the Services completed or in process prior to notice of such termination. All sections of this Agreement and the Supplier Agreement and any remedies for breach of this Agreement or the Supplier Agreement shall survive any termination or expiration.</p>
            <p>c. <span style={{textDecoration: "underline"}}>For Buyers</span> - Under any Buyer Agreement, if either Party breaches a material provision of the Buyer Agreement, the non-breaching Party may terminate this Agreement upon ten (10) days’ notice, unless the breach is cured within ten (10) days (except in the case of non-payment by Buyer, in which case ARDO shall have the right to terminate within five (5) days of such failure to cure). ARDO also may terminate this Agreement at any time, for any reason, without any further liability, upon thirty (30) days’ notice. Upon termination, the Parties agree to pay any and all unpaid, undisputed amounts due for the Services completed or in process prior to notice of such termination. All sections of this Agreement and the Buyer Agreement and any remedies for breach of this Agreement or the Buyer Agreement shall survive any termination or expiration hereof.</p>
            <h3>8. DISCLAIMER OF WARRANTIES.</h3>
            <p>a. The Services may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either by ARDO or by third-party providers, or because of other causes beyond our reasonable control, but ARDO shall use reasonable efforts to provide advance notice in writing or by email of any scheduled service disruption HOWEVER, THE SERVICES, INCLUDING THE SITE AND CONTENT, AND ALL SERVER AND NETWORK COMPONENTS ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT ANY WARRANTIES OF ANY KIND, AND ARDO EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOU ACKNOWLEDGE THAT ARDO DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE OR VIRUS-FREE, NOR DOES IT MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SERVICES, AND NO INFORMATION, ADVICE OR SERVICES OBTAINED BY YOU FROM ARDO OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS T&C.</p>
            <p>b. <span style={{textDecoration: "underline"}}>For Buyers</span> - ARDO represents and warrants that the Services will be performed in a professional and workmanlike manner. Each Party represents and warrants that: (a) they have the full right to perform this Agreement without conflict to any obligation they may have to others; (b) they will comply with all applicable laws in the course of performance under the Agreement (including, without limitation, in the case of Buyer, all applicable food safety handling, labeling, and other applicable food and health related laws and regulations); and (c) if either Party’s performance hereunder requires any license(s) or permit(s), such Party has all required licenses and permits and they are in full force and effect.</p>
            <h3>9. LIMITATION OF LIABILITY.</h3>
            <p>a. UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (WHETHER IN CONTRACT, TORT, OR OTHERWISE) SHALL ARDO BE LIABLE TO YOU OR ANY THIRD PARTY FOR (A) ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST SALES OR BUSINESS, LOST DATA, OR (B) FOR ANY DIRECT DAMAGES, COSTS, LOSSES OR LIABILITIES IN EXCESS OF THE FEES ACTUALLY PAID BY YOU IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO YOUR CLAIM OR, IF NO FEES APPLY, ONE HUNDRED ($100) U.S. DOLLARS. THE PROVISIONS OF THIS SECTION 8 ALLOCATE THE RISKS UNDER THIS T&C BETWEEN THE PARTIES, AND THE PARTIES HAVE RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO ENTER INTO THIS T&C.</p>
            <p>b. For Buyers -</p>
            <p><strong>UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (WHETHER IN CONTRACT, TORT OR OTHERWISE) SHALL ARDO BE LIABLE TO THE BUYER OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST SALES OR BUSINESS, OR LOST DATA. FURTHER, IN NO EVENT SHALL ARDO’S LIABILITY TO BUYER UNDER THIS AGREEMENT EXCEED 100% OF THE AMOUNT PAID BY BUYER TO ARDO IN THE 12 MONTHS PRIOR TO ANY INCIDENT GIVING RISE TO SUCH LIABILITY OR $25,000.00 - WHICHEVER AMOUNT IS LESS. THE PARTIES ACKNOWLEDGE THAT THE FOREGOING IS A FAIR ASSESSMENT AND ALLOCATION OF RISK BASED UPON THE SERVICES PROVIDED BY ARDO.</strong></p>
            <h3>10. Indemnification.</h3>
            <p>You shall defend, indemnify, and hold harmless ARDO from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, arising or resulting from your breach of this T&C, any of Your Content, or your other access, contribution to, use or misuse of the Services. ARDO shall provide notice to you of any such claim, suit or demand. ARDO reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this Section 10. In such case, you agree to cooperate with any reasonable requests assisting ARDO’s defense of such matter.</p>
            <h3>11. Assignment.</h3>
            <p>You may not assign this T&C without the prior written consent of ARDO, but ARDO may assign or transfer this T&C, in whole or in part, without restriction. Notwithstanding any assignment, you shall remain fully liable to ARDO for any payment obligations hereunder.</p>
            <h3>13. Miscellaneous.</h3>
            <p>If any provision of this T&C is found to be unenforceable, illegal, or otherwise invalid, that provision will be limited or eliminated to the minimum extent necessary so that this T&C will otherwise remain in full force and effect and enforceable. In connection with this T&C, the parties are acting as independent contractors and not as agents or partners. No agency, partnership, joint venture, or employment is created as a result of this T&C and you do not have any authority of any kind to bind ARDO in any respect whatsoever. The failure of ARDO to exercise or enforce any right or provision of this T&C shall not be a waiver of that right. ARDO may provide you with notices in the manner described in Section 1.3 above. All notices under this T&C shall be in writing and shall be deemed given when received if personally delivered; when receipt is electronically confirmed, if transmitted by email; upon delivery from a nationally recognized courier (e.g., SF); or three days after being sent by prepaid certified or registered Hong Kong mail to the address of the party to be noticed as set forth herein or to such other address as such party last provided to the other by written notice. Any notice to ARDO shall include a mandatory copy to: ARDO Group Limited, 50 Ma Tau Kok Road, Apartment 21K. </p>
            <h3>14. Governing Law.</h3>
            <p>This T&C shall be governed by the laws of the Hong Kong without regard to the principles of conflicts of law. Unless otherwise elected by ARDO in a particular instance, Hong Kong is the exclusive jurisdiction for any disputes and you hereby expressly agree to submit to the exclusive personal jurisdiction of such courts for the purpose of resolving any dispute relating to or in connection with your access to or use of the Services. In any action or proceeding to enforce rights under this T&C, the prevailing party will be entitled to recover costs and attorneys’ fees (including appellate proceedings).</p>
            <h3>15. Privacy.</h3>
            <p>Please visit <a href={"https://ardogroup.org"} target={"_blank"}>https://ardogroup.org</a> to understand how ARDO collects and uses personal information.</p>
            <p>COPYRIGHT AND LEGAL NOTICE. Copyright ©2024 ARDO Group Limited. All Rights Reserved.</p>
            <p>For further inquiries, contact us at info@ardogroup.org</p>
        </main>
    )
}
