name: Dev Backend

on:
  workflow_dispatch:

env:
  REGISTRY: "registry.digitalocean.com/ardogroup"
  IMAGE_NAME: "ardo-dev-backend"

jobs:
  # The "build" workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_RUN_ID) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_RUN_ID)

  # The "deploy" workflow
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean Droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_RUN_ID
          script: |
            # Install docker
            curl -fsSL https://get.docker.com | sh
            
            # Login to registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            
            # Stop running container
            docker stop $(echo $IMAGE_NAME)
            
            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            
            # Run a new container from a new image
            docker run -e ${{ secrets.dev.MONGO_URI }} -e ${{ secrets.dev.IS_DEV_MODE }} -e ${{ secrets.dev.SMTP_USER }} -e ${{ secrets.dev.SMTP_PASS }} -e ${{ secrets.dev.SMTP_HOST }} -e ${{ secrets.dev.SMTP_PORT }} -e ${{ secrets.dev.API_URI }} -e ${{ secrets.dev.CLIENT_URI }} -e ${{ secrets.dev.SPACE_KEY }} -e ${{ secrets.dev.SPACE_SECRET }} -e ${{ secrets.dev.SPACE_ENDPOINT }} -e ${{ secrets.dev.SPACE_REGION }} -e ${{ secrets.dev.SPACE_NAME }} -e ${{ secrets.dev.SPACE_HOST }} -d --restart always --name $(echo $IMAGE_NAME) $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_RUN_ID)