import classes from "./TermsOfUse.module.scss";

export default function TermsOfUse() {
    return (
        <main className={classes.terms}>
            <h1 style={{textTransform: "uppercase"}}>{'Terms of Use'}</h1>
            <p><strong>{'“Content” any information, materials, documents, text, images, video clips, directories, files, databases, listings, service, and/or mechanisms provided, produced, hosted by, linked to or accessed through use and/or provision of Sourcing'}</strong></p>
            <p><strong>{'"Information" information, data, content, analysis, news, reports, programmes, photographs, pictures, graphics, video, audio, software and other materials and services, communications, transmissions and other items, tangible or intangible'}</strong></p>
            <p><strong>{'"personal data" personally identifying information or sensitive data (including but not limited to names, ages, addresses, occupations, contacts, other personal details and credit card information)'}</strong></p>
            <p><strong>{'"Services" services include [service of ARDO ] and such other services as may be offered from time to time on the Website'}</strong></p>
            <p><strong>{'"ARDO", "we", "our" or "us" [ARDO]'}</strong></p>
            <p><strong>{'"ARDO Affiliates", "Our Affiliates" ARDO\'s agents or licensors, and their respective agents, officers, affiliates and employees'}</strong></p>
            <p><strong>{'"Terms of Use" the terms of use set forth below as amended from time to time'}</strong></p>
            <p><strong>{'"Third Party Provider" any provider of Information or services (including third party payment processors) on the Website other than ARDO'}</strong></p>
            <p><strong>{'"users", "you" or "your" any person who accesses the Website'}</strong></p>
            <p><strong>{'"Website" [website], including the Services offered therein, and any other website(s) from time to time hosted or linked up by ARDO'}</strong></p>
            <p><strong>{'PLEASE READ THE TERMS OF USE SET FORTH BELOW, AS THEY APPLY TO YOUR USE OF THE WEBSITE. YOUR USE OF THE WEBSITE SIGNIFIES YOUR ACCEPTANCE OF THESE TERMS OF USE AND AGREEMENT TO BE BOUND BY THEM AND ANY AND ALL OTHER APPLICABLE TERMS REFERENCED HEREIN ABSOLUTELY.'}</strong></p>
            <h2>{'1. Changes to Website'}</h2>
            <p>{'We may, in our sole discretion and at any time, without notice to you, add to, amend or remove any Information from the Website, or alter the presentation, substance, or functionality of the Website.'}</p>
            <h2>{'2. Change of Terms'}</h2>
            <p>{'We may amend the Terms of Use from time to time in our sole discretion without notice or liability to you. By continuing to use the Website following such amendments to the Terms of Use, you agree to be bound by such amendments.'}</p>
            <p><strong>{'In addition to these Terms of Use, the use of Services offered on the Website may be subject to further terms and conditions. In the event of any conflict, the specific Services terms and conditions shall prevail over these Terms of Use.'}</strong></p>
            <h2>{'3. User\'s Conduct'}</h2>
            <p>{'As a condition of your use of the Website, you must not:'}</p>
            <p><strong>{'(a) trespass, break into, access, use or attempt to trespass, break into, access or use any other parts of our servers, and/or any data areas for which you have not been authorised by us; (b) restrict or inhibit any other user from using and enjoying the Website; (c) post or transmit any unlawful, fraudulent, libellous, defamatory, obscene, pornographic, profane, threatening, abusive, hateful, offensive, or otherwise objectionable or unreasonable Information of any kind, including without limitation any transmissions constituting or encouraging conduct that may constitute a criminal offence, give rise to civil liability, or otherwise violate any local, state, national or foreign law; (d) post or transmit any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities or schemes or other unsolicited commercial communication, or engage in spamming or flooding; (e) post or transmit any Information or software which contains any virus, trojan horse, worm or other harmful component; (f) post, publish, transmit, reproduce, distribute, exploit or use in any way any Information obtained through the Website for or in connection with the following purposes:'}</strong></p>
            <p><strong>{'1. (i) conducting any direct marketing activities and/or disseminating or circulating any part of the content of any unsolicited publicity or advertising materials;'}</strong></p>
            <p><strong>{'2. (ii) advertising and/or promoting any goods and services;'}</strong></p>
            <p><strong>{'3. (iii) sale or exchange of any part of the Information obtained through the Website for any benefits, gain, profit or rewards; or'}</strong></p>
            <p><strong>{'4. (iv) any other commercial purposes; and/or(g) upload, post, publish, transmit, reproduce, or distribute in any way, Information obtained through the Website which is protected by copyright, or other proprietary right, or create derivative works with respect thereto, without the prior written permission of the copyright owner or rightholder.'}</strong></p>
            <p><strong>{'You have no rights in or to the Information available from time to time on the Website and you will not use the Information available from time to time on the Website in any manner or for any purpose, except as permitted under these Terms of Use.'}</strong></p>
            <h2>{'4. Access'}</h2>
            <p>{'We reserve the right at all times to prohibit or deny your access to the Website or any part thereof immediately and without notice, where we are of the opinion that you have breached any of the terms contained in the Terms of Use or that such prohibition or denial is appropriate, desirable or necessary in our sole discretion.'}</p>
            <p><strong>{'Whilst we implement appropriate security measures to control access to the Website (please see our Privacy Policy Statement for further details), you must keep your login details (if any) confidential and ensure that only you or your authorized employees access the Services for proper purposes.'}</strong></p>
            <h2>{'5. Third Party Information'}</h2>
                <p>{'The Information may contain Information provided by Third Party Providers or sourced by '}<strong>ARDO</strong>{' from other references or sources. The Information on the Website may not be regarded as any recommendation or endorsement by '}<strong>{'ARDO'}</strong>{' for any purpose with respect to any person, product or service.'}</p>
            <p><strong>{'ARDO is not responsible if any such Information is not up-to-date; ARDO does not separately verify such Information. Accordingly we do not accept any responsibility whatsoever in respect of such Information. Any use of and reliance on such Information is at your own risk.'}</strong></p>
            <p><strong>{'In particular, the views, comments and opinions expressed in the ARDO Forum do not represent the views of or any endorsement by ARDO. You are cautioned as to the reliability and accuracy of opinions expressed in the ARDO Forum.'}</strong></p>
            <h2>{'6. Links to and from the Website'}</h2>
            <p>{'The links on the Website may take you to other sites and you acknowledge and agree that '}<strong>ARDO</strong>{' and the '}<strong>ARDO</strong>{' Affiliates have no responsibility for the accuracy or availability of any Information provided by linked websites.'}</p>
            <p><strong>{'Links to other websites do not constitute an endorsement by ARDO of such websites or the Information, products, advertising or other materials available on those websites.'}</strong></p>
            <h2>{'7. Indemnity'}</h2>
            <p>{'You agree to on demand defend, indemnify and hold us and the '}<strong>ARDO</strong>{' Affiliates harmless from and against all liabilities, damages, claims, actions, costs and expenses (including without limitation legal fees), in connection with or arising from your breach of any provision in these Terms of Use and/or your use of the Website and /or the Information available from time to time on the Website for any purpose whatsoever (whether or not constituting a breach of any provision in these Terms of Use). We may, if necessary, participate in the defence of any claim or action and any negotiations for settlement. No settlement which may adversely affect our rights or obligations shall be made without our prior written approval. We reserve the right, at our own expense and on notice to you, to assume exclusive defence and control of any claim or action.'}</p>
            <h2>{'8. Intellectual Property Rights'}</h2>
            <p>{'All intellectual property rights subsisting in respect of the Website belong to '}<strong>ARDO</strong>{' or have been lawfully licensed to '}<strong>ARDO</strong>{' for use on the Website. All rights under applicable laws are hereby reserved. Except with the express permission of '}<strong>ARDO</strong>{', you are not allowed to upload, post, publish, reproduce, transmit or distribute in any way any component of the Website itself or create derivative works with respect thereto, as the Website is copyrighted under applicable laws.'}</p>
            <p><strong>{'ARDO is very serious about IPR infringement and has established guidelines to handle such cases. Please refer to our IPR Complaint Procedure and Guidelines .'}</strong></p>
            <h2>{'9. Limited Liability and Warranty'}</h2>
            <p>{'All Information available from time to time on the Website is for your general reference only. '}<strong>ARDO</strong>{' does not accept any responsibility whatsoever in respect of such Information.'}</p>
            <p><strong>{'YOUR ACCESS TO AND USE OF OUR WEBSITE IS AT YOUR SOLE RISK AND IS PROVIDED "AS IS," "AS AVAILABLE." THE WEBSITE IS FOR YOUR PERSONAL USE ONLY AND WE MAKE NO REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES ON MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE.'}</strong></p>
            <p><strong>{'OUR ENTIRE LIABILITY AND YOUR EXCLUSIVE REMEDY WITH RESPECT TO THE WEBSITE OR OTHERWISE, IS RE-PERFORMANCE OF DEFECTIVE SERVICES. IN JURISDICTIONS WHICH DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN TYPES OF LIABILITY, OUR LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. WE DO NOT ENDORSE, WARRANT OR GUARANTEE ANY INFORMATION, MATERIAL, PRODUCT OR SERVICE OFFERED THROUGH US OR OUR WEBSITE. WE ARE NOT AND WILL NOT BE A PARTY TO ANY TRANSACTION BETWEEN YOU AND ANY THIRD PARTY.'}</strong></p>
            <p><strong>{'Neither ARDO nor any of the ARDO’s Affiliates shall guarantee or assume any responsibility that: 1. the Information on the Website is accurate, adequate, current or reliable, or may be used for any purpose other than for general reference; 2. the Information on the Website is free of defect, error, omission, virus or anything which may change, erase, add to or damage your software, data or equipment; 3. messages sent through the internet including in connection with the Services will be free from interception, corruption, error, delay or loss; 4. access to the Website will be available or be uninterrupted; 5. use of the Website or Services will achieve any particular result; or 6. defects in the Website will be corrected.'}</strong></p>
            <p><strong>{'Without limiting the generality of the foregoing, in no event will the ARDO or the ARDO’s Affiliates be liable to you or any other person for any direct, indirect, incidental, special, punitive or consequential loss or damages, including any loss of business or profit, arising out of any use, or inability to use, the Information or the Services, even if ARDO or the ARDO‘s Affiliates have been advised of the possibility of such loss or damages.'}</strong></p>
            <p><strong>{'In addition, ARDO accepts no responsibility for or liability in respect of Information or services provided by Third Party Providers, nor does it endorse such Third Party Providers. You acknowledge and accept that any dispute in relation to such Information or services is unrelated to ARDO and is solely a matter between you and such Third Party Provider.'}</strong></p>
            <p><strong>{'You will exercise and rely solely on your own skill and judgment in your use and interpretation of the Information and use of the Services. You are responsible to ensure that your use of the Information obtained through the Website and the Services in any way for any purpose whatsoever complies with all applicable legal requirements, including without limitation, the data protection law applicable to you.'}</strong></p>
            <p><strong>{'Without prejudice to the foregoing, if your use of the Services does not proceed satisfactorily and/or where applicable you do not receive appropriate responses to such use from ARDO as set out in these Terms of Use or otherwise, you are advised to contact us by email to [email] or by telephone at [phone]. No such lack of response shall be deemed to constitute any acquiescence or waiver.'}</strong></p>
            <p><strong>{'The limitation of liability contained in these Terms of Use will apply to the fullest extent permitted by applicable laws.'}</strong></p>
            <h2>{'10. Privacy Policy'}</h2>
            <p><strong>{'For information about our privacy policies and practices, please refer to our Privacy Policy Statement. You agree to the use and disclosure of your information in the manner set out in our Privacy Policy Statement (as updated from time to time). Where personal data is collected in connection with the Services, you should also have reference to the relevant user agreements linked to the form through which your personal data is collected.'}</strong></p>
            <p><strong>{'For information on our use of cookies, please also refer to our Privacy Policy Statement.'}</strong></p>
            <h2>{'11. Partial Invalidity'}</h2>
            <p>{'The illegality, invalidity or unenforceability of any provision of these Terms of Use under the law of any jurisdiction shall not affect its legality, validity or enforceability under the laws of any other jurisdiction nor the legality, validity or enforceability of any other provision.'}</p>
            <h2>{'12. Several Users'}</h2>
            <p>{'If there are two or more persons adhering to these Terms of Use as user, their liability under the Terms of Use is joint and several, and their rights are joint.'}</p>
            <h2>{'13. Miscellaneous'}</h2>
            <p>{'No waiver of any breach under these Terms of Use will amount to a waiver of any other breach. The headings in these Terms of Use are for convenience only and do not affect interpretation.'}</p>
            <h2>{'14. Termination'}</h2>
            <p>{'We may, in our sole discretion and at any time, without prior notice to you and without cause, terminate all or any part of our Services to you and consequentially prohibit your right to access to the Services and/or the Website and remove any information and data linked to your profile or registered account.'}</p>
            <h2>{'15. Governing Law and Jurisdiction'}</h2>
            <p>{'These Terms of Use shall be governed by the law of the Hong Kong Special Administrative Region. You agree to submit to the non-exclusive jurisdiction of the Hong Kong courts.'}</p>
            <h2>{'16. Chinese Version'}</h2>
            <p>{'If there is any conflict or difference between the Chinese version of the Terms of Use and its English version, the English version prevails. If any part of the Chinese version is unclear, reference should be made to the English version. The Chinese version may not be translated into English for the purpose of comparing with or interpreting the English version.'}</p>
        </main>
    )
}
