// code generated by gen.go
// DO NOT EDIT.
package core

const (
	TXT_UNKNOWN_ERROR               TxtKey = 1
	TXT_EMPTY_FIRSTNAME             TxtKey = 2
	TXT_FIRSTNAME_TOO_SHORT         TxtKey = 3
	TXT_FIRSTNAME_TOO_LONG          TxtKey = 4
	TXT_EMPTY_LASTNAME              TxtKey = 5
	TXT_LASTNAME_TOO_SHORT          TxtKey = 6
	TXT_LASTNAME_TOO_LONG           TxtKey = 7
	TXT_EMPTY_PASSWORD              TxtKey = 8
	TXT_PASSWORD_TOO_SHORT          TxtKey = 9
	TXT_PASSWORD_TOO_LONG           TxtKey = 10
	TXT_INVALID_PASSWORD            TxtKey = 11
	TXT_SAME_PASSWORD               TxtKey = 12
	TXT_EMPTY_EMAIL                 TxtKey = 13
	TXT_INVALID_EMAIL               TxtKey = 14
	TXT_EMAIL_DOESNT_EXIST          TxtKey = 15
	TXT_EMAIL_ALREADY_EXISTS        TxtKey = 16
	TXT_INVALID_USER_TYPE           TxtKey = 17
	TXT_USER_NOT_FOUND              TxtKey = 18
	TXT_ACCOUNT_NOT_ACTIVE          TxtKey = 19
	TXT_EMPTY_MERCHANT_ROLE         TxtKey = 20
	TXT_INVALID_MERCHANT_ROLE       TxtKey = 21
	TXT_INVALID_CURRENCY            TxtKey = 22
	TXT_EMPTY_PHONE_NUMBER          TxtKey = 23
	TXT_EMPTY_ADDRESS               TxtKey = 24
	TXT_INVALID_PRODUCT_STATUS      TxtKey = 25
	TXT_INVALID_PRODUCT_PRICE       TxtKey = 26
	TXT_INVALID_PRODUCT_QUANTITY    TxtKey = 27
	TXT_INVALID_PRODUCT_IMG_URL     TxtKey = 28
	TXT_INVALID_REVIEW_RATING       TxtKey = 29
	TXT_INVALID_REVIEW_COMMENT      TxtKey = 30
	TXT_WRONG_MLSTRING_FORMAT       TxtKey = 31
	TXT_USER_AGENT_EMPTY            TxtKey = 32
	TXT_USER_SESSION_ALREADY_EXISTS TxtKey = 33
	TXT_USER_SESSION_NOT_FOUND      TxtKey = 34
	TXT_USER_ALREADY_EXISTS         TxtKey = 35
	TXT_UNAUTHORIZED                TxtKey = 36
	TXT_EMPTY_ORG_NAME              TxtKey = 37
	TXT_ORG_NAME_TOO_SHORT          TxtKey = 38
	TXT_ORG_NAME_TOO_LONG           TxtKey = 39
	TXT_DO_NOT_HAVE_AN_ACCESS       TxtKey = 40
	TXT_OLD_PASSWORD_DOES_NOT_MATCH TxtKey = 41
	TXT_EMPTY_ORG_LOGO              TxtKey = 42
	TXT_ORG_NOT_FOUND               TxtKey = 43
	TXT_USER_ALREADY_IN_ORG         TxtKey = 44
	TXT_FILE_IS_NIL                 TxtKey = 45
	TXT_UPLOADED_IMG_INVALID        TxtKey = 46
	TXT_FILE_NOT_FOUND              TxtKey = 47
	TXT_EMPTY_LANG                  TxtKey = 48
	TXT_INVALID_LANG                TxtKey = 49
)

var Txts = TxtResource{
	TXT_UNKNOWN_ERROR: MlString{
		RU: `Неизвестная ошибка`,
		EN: `Unknown error`,
	},
	TXT_EMPTY_FIRSTNAME: MlString{
		RU: `Имя не может быть пустым`,
		EN: `First name can not be empty`,
	},
	TXT_FIRSTNAME_TOO_SHORT: MlString{
		RU: `Имя должно быть не менее 6 символов`,
		EN: `First name must be at least 6 characters`,
	},
	TXT_FIRSTNAME_TOO_LONG: MlString{
		RU: `Имя должно быть не более 50 символов`,
		EN: `First name must be no more than 50 characters`,
	},
	TXT_EMPTY_LASTNAME: MlString{
		RU: `Фамилия не может быть пустой`,
		EN: `Last name can not be empty`,
	},
	TXT_LASTNAME_TOO_SHORT: MlString{
		RU: `Фамилия должна быть не менее 6 символов`,
		EN: `Last name must be at least 6 characters`,
	},
	TXT_LASTNAME_TOO_LONG: MlString{
		RU: `Фамилия должна быть не более 50 символов`,
		EN: `Last name must be no more than 50 characters`,
	},
	TXT_EMPTY_PASSWORD: MlString{
		RU: `Пароль не может быть пустым`,
		EN: `Password can not be empty`,
	},
	TXT_PASSWORD_TOO_SHORT: MlString{
		RU: `Пароль должен быть не менее 6 символов`,
		EN: `Password must be at least 6 characters`,
	},
	TXT_PASSWORD_TOO_LONG: MlString{
		RU: `Пароль должен быть не более 32 символов`,
		EN: `Password must be no more than 32 characters`,
	},
	TXT_INVALID_PASSWORD: MlString{
		RU: `Неверный пароль`,
		EN: `Invalid password`,
	},
	TXT_SAME_PASSWORD: MlString{
		RU: `Новый пароль не может совпадать со старым`,
		EN: `New password can not be the same as the old one`,
	},
	TXT_EMPTY_EMAIL: MlString{
		RU: `Email не может быть пустым`,
		EN: `Email can not be empty`,
	},
	TXT_INVALID_EMAIL: MlString{
		RU: `Неверный формат email`,
		EN: `Invalid email`,
	},
	TXT_EMAIL_DOESNT_EXIST: MlString{
		RU: `Пользователь с таким email не существует`,
		EN: `User with this email does not exist`,
	},
	TXT_EMAIL_ALREADY_EXISTS: MlString{
		RU: `Пользователь с таким email уже существует`,
		EN: `User with this email already exists`,
	},
	TXT_INVALID_USER_TYPE: MlString{
		RU: `Неверный тип пользователя`,
		EN: `Invalid user type`,
	},
	TXT_USER_NOT_FOUND: MlString{
		RU: `Пользователь не найден`,
		EN: `User not found`,
	},
	TXT_ACCOUNT_NOT_ACTIVE: MlString{
		RU: `Аккаунт не активирован`,
		EN: `Account not activated`,
	},
	TXT_EMPTY_MERCHANT_ROLE: MlString{
		RU: `Роль не может быть пустой`,
		EN: `Role can not be empty`,
	},
	TXT_INVALID_MERCHANT_ROLE: MlString{
		RU: `Неверная роль`,
		EN: `Invalid role`,
	},
	TXT_INVALID_CURRENCY: MlString{
		RU: `Неверная валюта`,
		EN: `Invalid currency`,
	},
	TXT_EMPTY_PHONE_NUMBER: MlString{
		RU: `Номер телефона не может быть пустым`,
		EN: `Phone number can not be empty`,
	},
	TXT_EMPTY_ADDRESS: MlString{
		RU: `Адрес не может быть пустым`,
		EN: `Address can not be empty`,
	},
	TXT_INVALID_PRODUCT_STATUS: MlString{
		RU: `Неверный статус продукта`,
		EN: `Invalid product status`,
	},
	TXT_INVALID_PRODUCT_PRICE: MlString{
		RU: `Неверная цена продукта`,
		EN: `Invalid product price`,
	},
	TXT_INVALID_PRODUCT_QUANTITY: MlString{
		RU: `Неверное количество продукта`,
		EN: `Invalid product quantity`,
	},
	TXT_INVALID_PRODUCT_IMG_URL: MlString{
		RU: `Неверный URL изображения продукта`,
		EN: `Invalid product image URL`,
	},
	TXT_INVALID_REVIEW_RATING: MlString{
		RU: `Рейтинг отзыва должен быть от 1 до 5`,
		EN: `Review rating must be from 1 to 5`,
	},
	TXT_INVALID_REVIEW_COMMENT: MlString{
		RU: `Комментарий отзыва должен быть не более 250 символов`,
		EN: `Review comment must be no more than 250 characters`,
	},
	TXT_WRONG_MLSTRING_FORMAT: MlString{
		RU: `Неверный формат mlstring`,
		EN: `Wrong mlstring format`,
	},
	TXT_USER_AGENT_EMPTY: MlString{
		RU: `User agent не может быть пустым`,
		EN: `User agent can not be empty`,
	},
	TXT_USER_SESSION_ALREADY_EXISTS: MlString{
		RU: `Сессия уже существует`,
		EN: `Session already exists`,
	},
	TXT_USER_SESSION_NOT_FOUND: MlString{
		RU: `Сессия не найдена`,
		EN: `Session not found`,
	},
	TXT_USER_ALREADY_EXISTS: MlString{
		RU: `Пользователь уже существует`,
		EN: `User already exists`,
	},
	TXT_UNAUTHORIZED: MlString{
		RU: `Неавторизованный запрос`,
		EN: `Unauthorized request`,
	},
	TXT_EMPTY_ORG_NAME: MlString{
		RU: `Название организации не может быть пустым`,
		EN: `Organization name can not be empty`,
	},
	TXT_ORG_NAME_TOO_SHORT: MlString{
		RU: `Название организации должно быть не менее 3 символов`,
		EN: `Organization name must be at least 6 characters`,
	},
	TXT_ORG_NAME_TOO_LONG: MlString{
		RU: `Название организации должно быть не более 50 символов`,
		EN: `Organization name must be no more than 50 characters`,
	},
	TXT_DO_NOT_HAVE_AN_ACCESS: MlString{
		RU: `У вас нет доступа`,
		EN: `You do not have an access`,
	},
	TXT_OLD_PASSWORD_DOES_NOT_MATCH: MlString{
		RU: `Старый пароль не совпадает`,
		EN: `Old password does not match`,
	},
	TXT_EMPTY_ORG_LOGO: MlString{
		RU: `Логотип организаций не может быть пустым`,
		EN: ` Organization logo can not be empty`,
	},
	TXT_ORG_NOT_FOUND: MlString{
		RU: `Организация не найдена`,
		EN: `Organization not found`,
	},
	TXT_USER_ALREADY_IN_ORG: MlString{
		RU: `Пользователь уже состоит в организации`,
		EN: `User already in organization`,
	},
	TXT_FILE_IS_NIL: MlString{
		RU: `Файл не может быть пустым`,
		EN: `File can not be empty`,
	},
	TXT_UPLOADED_IMG_INVALID: MlString{
		RU: `Загруженное изображение неверно`,
		EN: `Uploaded image is invalid`,
	},
	TXT_FILE_NOT_FOUND: MlString{
		RU: `Файл не найден`,
		EN: `File not found`,
	},
	TXT_EMPTY_LANG: MlString{
		RU: `Предпочитаемый язык интерфейса не может быть пустым`,
		EN: `Preferred language of web-interface can not be empty`,
	},
	TXT_INVALID_LANG: MlString{
		RU: `Данный язык отсутствует в системе`,
		EN: `This language is not available in the system`,
	},
}

func GetTxtKeyAsString(k TxtKey) string {
	switch k {
	case TXT_UNKNOWN_ERROR:
		return "unknown_error"
	case TXT_EMPTY_FIRSTNAME:
		return "empty_firstname"
	case TXT_FIRSTNAME_TOO_SHORT:
		return "firstname_too_short"
	case TXT_FIRSTNAME_TOO_LONG:
		return "firstname_too_long"
	case TXT_EMPTY_LASTNAME:
		return "empty_lastname"
	case TXT_LASTNAME_TOO_SHORT:
		return "lastname_too_short"
	case TXT_LASTNAME_TOO_LONG:
		return "lastname_too_long"
	case TXT_EMPTY_PASSWORD:
		return "empty_password"
	case TXT_PASSWORD_TOO_SHORT:
		return "password_too_short"
	case TXT_PASSWORD_TOO_LONG:
		return "password_too_long"
	case TXT_INVALID_PASSWORD:
		return "invalid_password"
	case TXT_SAME_PASSWORD:
		return "same_password"
	case TXT_EMPTY_EMAIL:
		return "empty_email"
	case TXT_INVALID_EMAIL:
		return "invalid_email"
	case TXT_EMAIL_DOESNT_EXIST:
		return "email_doesnt_exist"
	case TXT_EMAIL_ALREADY_EXISTS:
		return "email_already_exists"
	case TXT_INVALID_USER_TYPE:
		return "invalid_user_type"
	case TXT_USER_NOT_FOUND:
		return "user_not_found"
	case TXT_ACCOUNT_NOT_ACTIVE:
		return "account_not_active"
	case TXT_EMPTY_MERCHANT_ROLE:
		return "empty_merchant_role"
	case TXT_INVALID_MERCHANT_ROLE:
		return "invalid_merchant_role"
	case TXT_INVALID_CURRENCY:
		return "invalid_currency"
	case TXT_EMPTY_PHONE_NUMBER:
		return "empty_phone_number"
	case TXT_EMPTY_ADDRESS:
		return "empty_address"
	case TXT_INVALID_PRODUCT_STATUS:
		return "invalid_product_status"
	case TXT_INVALID_PRODUCT_PRICE:
		return "invalid_product_price"
	case TXT_INVALID_PRODUCT_QUANTITY:
		return "invalid_product_quantity"
	case TXT_INVALID_PRODUCT_IMG_URL:
		return "invalid_product_img_url"
	case TXT_INVALID_REVIEW_RATING:
		return "invalid_review_rating"
	case TXT_INVALID_REVIEW_COMMENT:
		return "invalid_review_comment"
	case TXT_WRONG_MLSTRING_FORMAT:
		return "wrong_mlstring_format"
	case TXT_USER_AGENT_EMPTY:
		return "user_agent_empty"
	case TXT_USER_SESSION_ALREADY_EXISTS:
		return "user_session_already_exists"
	case TXT_USER_SESSION_NOT_FOUND:
		return "user_session_not_found"
	case TXT_USER_ALREADY_EXISTS:
		return "user_already_exists"
	case TXT_UNAUTHORIZED:
		return "unauthorized"
	case TXT_EMPTY_ORG_NAME:
		return "empty_org_name"
	case TXT_ORG_NAME_TOO_SHORT:
		return "org_name_too_short"
	case TXT_ORG_NAME_TOO_LONG:
		return "org_name_too_long"
	case TXT_DO_NOT_HAVE_AN_ACCESS:
		return "do_not_have_an_access"
	case TXT_OLD_PASSWORD_DOES_NOT_MATCH:
		return "old_password_does_not_match"
	case TXT_EMPTY_ORG_LOGO:
		return "empty_org_logo"
	case TXT_ORG_NOT_FOUND:
		return "org_not_found"
	case TXT_USER_ALREADY_IN_ORG:
		return "user_already_in_org"
	case TXT_FILE_IS_NIL:
		return "file_is_nil"
	case TXT_UPLOADED_IMG_INVALID:
		return "uploaded_img_invalid"
	case TXT_FILE_NOT_FOUND:
		return "file_not_found"
	case TXT_EMPTY_LANG:
		return "empty_lang"
	case TXT_INVALID_LANG:
		return "invalid_lang"

	default:
		return ""
	}
}
